version: '3'

volumes:
  pb_volume:

services:
  pocketbase:
    build:
      context: ./pocketbase

    ports:
      - 8090:8090

    command: ["/pocketbase/pocketbase", "serve", "--http", "0.0.0.0:8090"]

    volumes:
      - pb_volume:/pocketbase

  frontend-dev:
    build:
      context: ./frontend/MASSter-frontend

    ports:
      - 8080:8080

    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "8080"]

  preprocessor:
    build:
      context: model/preprocessor/docker

    environment:
      - PB_LINK=http://pocketbase:8090/
      - PB_LOGIN=dev@email.local
      - PB_PWD=1234567890
      - COL_NAME=text_generation_mvp

  generator:
    build:
      context: model/generator/docker

    environment:
      - PB_LINK=http://pocketbase:8090/
      - PB_LOGIN=dev@email.local
      - PB_PWD=1234567890
      - COL_NAME=text_generation_mvp
